import type { Metadata } from 'next'
import { Plus_Jakarta_Sans as PlusJakartaSans, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const plusJakartaSans = PlusJakartaSans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-plusjakartasans',
})

export const metadata: Metadata = {
  title: 'ignite-call',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${plusJakartaSans.variable} bg-zinc-950 text-zinc-100 antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
